export namespace Intents {
    const GUILDS: number;
    const GUILD_MEMBERS: number;
    const GUILD_BANS: number;
    const GUILD_EMOJIS_AND_STICKERS: number;
    const GUILD_INTEGRATIONS: number;
    const GUILD_WEBHOOKS: number;
    const GUILD_INVITES: number;
    const GUILD_VOICE_STATES: number;
    const GUILD_PRESENCES: number;
    const GUILD_MESSAGES: number;
    const GUILD_MESSAGE_REACTIONS: number;
    const GUILD_MESSAGE_TYPING: number;
    const DIRECT_MESSAGES: number;
    const DIRECT_MESSAGE_REACTIONS: number;
    const DIRECT_MESSAGE_TYPING: number;
    const MESSAGE_CONTENT: number;
    const GUILD_SCHEDULED_EVENTS: number;
    const AUTO_MODERATION_CONFIGURATION: number;
    const AUTO_MODERATION_EXECUTION: number;
}
export const socket_close: {
    1000: string;
    1002: string;
    1005: string;
    1006: string;
    1011: string;
    1012: string;
    4000: string;
    4001: string;
    4002: string;
    4003: string;
    4004: string;
    4005: string;
    4007: string;
    4008: string;
    4009: string;
    4010: string;
    4011: string;
    4012: string;
    4013: string;
    4014: string;
};
export const userFlags: {
    "Discord Employee": number;
    "Partnered Server Owner": number;
    "HypeSquad Events Member": number;
    "Bug Hunter Level 1": number;
    "House Bravery Member": number;
    "House Brilliance Member": number;
    "House Balance Member": number;
    "Early Nitro Supporter": number;
    "User is a team": number;
    "Bug Hunter Level 2": number;
    "Verified Bot": number;
    "Early Verified Bot Developer": number;
    "Discord Certified Moderator": number;
    "Bot uses only HTTP interactions and is shown in the online member list": number;
};
export namespace permissionNames {
    const CREATE_INSTANT_INVITE: number;
    const KICK_MEMBERS: number;
    const BAN_MEMBERS: number;
    const ADMINISTRATOR: number;
    const MANAGE_CHANNELS: number;
    const MANAGE_GUILD: number;
    const ADD_REACTIONS: number;
    const VIEW_AUDIT_LOG: number;
    const PRIORITY_SPEAKER: number;
    const STREAM: number;
    const VIEW_CHANNEL: number;
    const SEND_MESSAGES: number;
    const SEND_TTS_MESSAGES: number;
    const MANAGE_MESSAGES: number;
    const EMBED_LINKS: number;
    const ATTACH_FILES: number;
    const READ_MESSAGE_HISTORY: number;
    const MENTION_EVERYONE: number;
    const USE_EXTERNAL_EMOJIS: number;
    const VIEW_GUILD_INSIGHTS: number;
    const CONNECT: number;
    const SPEAK: number;
    const MUTE_MEMBERS: number;
    const DEAFEN_MEMBERS: number;
    const MOVE_MEMBERS: number;
    const USE_VAD: number;
    const CHANGE_NICKNAME: number;
    const MANAGE_NICKNAMES: number;
    const MANAGE_ROLES: number;
    const MANAGE_WEBHOOKS: number;
    const MANAGE_EMOJIS_AND_STICKERS: number;
    const USE_APPLICATION_COMMANDS: number;
    const REQUEST_TO_SPEAK: number;
    const MANAGE_EVENTS: number;
    const MANAGE_THREADS: number;
    const CREATE_PUBLIC_THREADS: number;
    const CREATE_PRIVATE_THREADS: number;
    const USE_EXTERNAL_STICKERS: number;
    const SEND_MESSAGES_IN_THREADS: number;
    const USE_EMBEDDED_ACTIVITIES: number;
    const MODERATE_MEMBERS: number;
}
//# sourceMappingURL=enum.d.ts.map