declare function _default(): string;
declare function _default(): string;
export { _default as default };
export declare function year(): number;
export declare function year(): number;
export declare function month(): string;
export declare function month(): string;
export declare function day(): string;
export declare function day(): string;
export declare function hours(): number;
export declare function hours(): number;
export declare function minutes(): string;
export declare function minutes(): string;
export declare function seconds(): string;
export declare function seconds(): string;
export declare function mseconds(): string;
export declare function mseconds(): string;
export declare function UTCdefault(): string;
export declare function UTCdefault(): string;
export declare function UTCyear(): number;
export declare function UTCyear(): number;
export declare function UTCmonth(): string;
export declare function UTCmonth(): string;
export declare function UTCday(): string;
export declare function UTCday(): string;
export declare function UTChours(): number;
export declare function UTChours(): number;
export declare function UTCminutes(): string;
export declare function UTCminutes(): string;
export declare function UTCseconds(): string;
export declare function UTCseconds(): string;
export declare function UTCmseconds(): string;
export declare function UTCmseconds(): string;
//# sourceMappingURL=timestamp.d.ts.map