module.exports = {
    'newREQUEST': (path, body = {}, audit = false, reason = null) => {
        return {
            url: encodeURI("discord.com"),
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bot ${process.env.token}`,
                'X-Audit-Log-Reason': (audit && reason) ?? undefined
            },
            path: encodeURI(`/api/${path}`),
            body: Object.keys(body).length ? JSON.stringify(body) : ''
        }
    },
    'newStructure': (type) => {
        if (typeof type != 'string') return {};

        type = type.toLowerCase();
        const structures = {
            "user": {
                "id": null,
                "username": null,
                "discriminator": null,
                "avatar": null,
                "bot": null,
                "system": null,
                "mfa_enabled": null,
                "banner": null,
                "accent_color": null,
                "locale": null,
                "verified": null,
                "email": null,
                "flags": null,
                "premium_type": null,
                "public_flags": null,
            },
            "member": {
                "user": null,
                "nick": null,
                "avatar": null,
                "roles": null,
                "joined_at": null,
                "deaf": null,
                "mute": null
            },
            "thread_member": {
                "id": null,
                "user_id": null,
                "join_timestamp": null,
                "flags": null,
            },
            "message": {
                "content": null,
                "tts": null,
                "embeds": null,
                "allowed_mentions": null,
                "message_reference": null,
                "components": null,
                "sticker_ids": null,
                "files": null,
                "payload_json": null,
                "attachments": null,
                "flags": null,
            },
            "embed": {
                "title": null,
                "type": null,
                "description": null,
                "url": null,
                "timestamp": null,
                "color": null,
                "footer": null,
                "image": null,
                "thumbnail": null,
                "video": null,
                "provider": null,
                "author": null,
                "fields": null,
            },
            "overwrite": {
                "id": null,
                "type": null,
                "allow": null,
                "deny": null,
            },
            "channel": {
                "id": null,
                "type": null,
                "guild_id": null,
                "position": null,
                "permission_overwrites": null,
                "name": null,
                "topic": null,
                "nsfw": null,
                "last_message_id": null,
                "bitrate": null,
                "user_limit": null,
                "rate_limit_per_user": null,
                "recipients": null,
                "icon": null,
                "owner_id": null,
                "application_id": null,
                "parent_id": null,
                "last_pin_timestamp": null,
                "rtc_region": null,
                "video_quality_mode": null,
                "message_count": null,
                "member_count": null,
                "thread_metadata": null,
                "member": null,
                "default_auto_archive_duration": null,
                "permissions": null,
                "flags": null,
                "total_message_sent": null,
                "available_tags": null,
                "applied_tags": null,
                "default_reaction_emoji": null,
                "default_thread_rate_limit_per_user": null,
                "default_sort_order": null,
            },
            "thread_metadata": {
                "archived": null,
                "archive_timestamp": null,
                "auto_archive_duration": null,
                "locked": null,
            },
            "interaction": {
                "id": null,
                "application_id": null,
                "type": null,
                "data": null,
                "guild_id": null,
                "channel_id": null,
                "member": null,
                "user?": null,
                "token": null,
                "version": null,
                "message": null,
                "app_permissions": null,
                "locale": null,
                "guild_locale": null,
            },
            "guild": {
                "id": null,
                "name": null,
                "icon": null,
                "icon_hash": null,
                "splash": null,
                "discovery_splash": null,
                "owner *": null,
                "owner_id": null,
                "permissions *": null,
                "region **": null,
                "afk_channel_id": null,
                "afk_timeout": null,
                "widget_enabled": null,
                "widget_channel_id": null,
                "verification_level": null,
                "default_message_notifications": null,
                "explicit_content_filter": null,
                "roles": null,
                "emojis": null,
                "features": null,
                "mfa_level": null,
                "application_id": null,
                "system_channel_id": null,
                "system_channel_flags": null,
                "rules_channel_id": null,
                "max_presences": null,
                "max_members": null,
                "vanity_url_code": null,
                "description": null,
                "banner": null,
                "premium_tier": null,
                "premium_subscription_count": null,
                "preferred_locale": null,
                "public_updates_channel_id": null,
                "max_video_channel_users": null,
                "approximate_member_count": null,
                "approximate_presence_count": null,
                "welcome_screen": null,
                "nsfw_level": null,
                "stickers": null,
                "premium_progress_bar_enabled": null,
            },
            "application": {
                "id": null,
                "name": null,
                "icon": null,
                "description": null,
                "rpc_origins": null,
                "bot_public": null,
                "bot_require_code_grant": null,
                "terms_of_service_url": null,
                "privacy_policy_url": null,
                "owner": null,
                "summary (deprecated)": null,
                "verify_key": null,
                "team": null,
                "guild_id": null,
                "primary_sku_id": null,
                "slug": null,
                "cover_image": null,
                "flags": null,
                "tags": null,
                "install_params": null,
                "custom_install_url": null,
            },
            "application_command": {
                "id": null,
                "type": null,
                "application_id": null,
                "guild_id": null,
                "name": null,
                "name_localizations": null,
                "description": null,
                "description_localizations": null,
                "options": null,
                "default_member_permissions": null,
                "dm_permission": null,
                "default_permission": null,
                "version": null,
            }

        };
        return structures[type] ?? {}
    }
}